version: "3"
services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer-ce:/data
    ports:
      - [LOCAL_PORT]:[CONTAINER_PORT]
    restart: always
  
# run this headless in term \o/
