version: "3"
services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/portainer-ce:/data
    ports:
      - 9000:9000
    restart: always
    labels:
      - flame.type=application
      - flame.name=Portainer
      - flame.url=[[flame-url]]
      - flame.icon=jellyfish-outline
