version: "3"
services:  
  plex-media-server:
    container_name: plex-media-server
    image: plexinc/pms-docker:latest
    environment:
      - TZ=America/New_York
      - PLEX_GID=[GID]
      - PLEX_UID=[UID]
    volumes:
      - /volume1/data/media:/media:rw
      - /volume1/docker/plex/transcode:/transcode:rw
      - /volume1/docker/plex/data:/data:rw
      - /volume1/docker/plex/config:/config:rw
    network_mode: host
    restart: always
    labels:
      - flame.type=application
      - flame.name=Plex
      - flame.url=[[flame=url]]
      - flame.icon=cat
