version: "3"
services:
  komga:
    container_name: komga
    image: gotson/komga:latest
    environment:
      - TZ=America/New_York
      - GUID=[[GUID]]
      - PUID=[[PUID]]
    volumes:
      - /volume1/library/Manga:/manga:rw
      - /volume1/docker/komga/config:/config:rw
      - /volume1/docker/komga/data:/data:rw
    ports:
      - 7080:8080
    restart: always
    labels:
      - flame.type=application
      - flame.name=Komga
      - flame.url=[[flame-url]]
      - flame.icon=snail
