version: "3"
services:
  komga:
    container_name: komga
    image: gotson/komga:latest
    environment:
      - TZ=America/New_York
      - GUID=100
      - PUID=1028
    volumes:
      - /volume1/docker/komga/data:/data:rw
      - /volume1/docker/komga/config:/config:rw
    ports:
      - 7080:8080
    restart: always