version: "3"
services: 
 calibre-web:
    container_name: calibre-web 
    image: linuxserver/calibre-web:latest
    environment:
      - TZ=America/New_York
      - PGID=100
      - PUID=1028
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /volume1/library/Books:/books:rw
      - /volume1/docker/calibre-web/config:/config:rw
    ports:
      - 8083:8083
    restart: always