version: "3"
services: 
 calibre-web:
    container_name: calibre-web 
    image: linuxserver/calibre-web:latest
    environment:
      - TZ=America/New_York
      - PGID=[GID]
      - PUID=[PUID]
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /volume1/library/Books:/books:rw
      - /volume1/docker/calibre-web/config:/config:rw
    ports:
      - [LOCAL_PORT]:[CONTAINER_PORT]
    restart: always

# this is run as part of the calibre stack in portainer
