version: "3"
services:
  calibre:
    container_name: calibre
    image: linuxserver/calibre:latest
    environment:
      - TZ=America/New_York
      - PGID=100
      - PUID=1028
    volumes:
      - /volume1/library/Books:/config/Calibre_Library:rw
      - /volume1/docker/calibre/upload:/upload:rw
      - /volume1/docker/calibre/plugins:/plugins:rw
      - /volume1/docker/calibre/config:/config:rw
    ports:
      - 24880:8080
    restart: always