version: "3"
services:
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    environment:
      - TZ=America/New_York
      - GUID=100
      - PUID=1028    
    volumes:
      - /volume1/docker/organizr/config:/config:rw
    ports:
      - 8286:443
      - 8285:80
    restart: always