version: "3"
services:
  organizr:
    container_name: organizr
    image: organizr/organizr:latest
    environment:
      - TZ=America/New_York
      - GUID=[GID]
      - PUID=[PID]   
    volumes:
      - /volume1/docker/organizr/config:/config:rw
    ports:
      - [LOCAL_PORT]:[CONTAINER_PORT]
      - [LOCAL_PORT]:[CONTAINER_PORT]
    restart: always
