version: "3"
services:
  syncthing:
    container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      - TZ=America/New_York
      - PGID=[GID]
      - PUID=[PID]
    volumes:
      - /volume1/docker/syncthing/config:/config
      - /volume1/docker/syncthing/data1:/data1
      - /volume1/docker/syncthing/data2:/data2
    ports:
      - [LOCAL_PORT]:[CONTAINER_PORT]
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

# default ports from lscr.io
